#!/usr/bin/env groovy
// shebang tells most editors to treat as groovy (syntax highlights, formatting, etc)

pipeline {
    agent {
		docker {image 'node:16-apine'}
	}
	environment {
		CI = true
		ARTIFACTORY_ACCESS_TOKEN = credentials('artifactory-access-token')
	}
    stages {
        // implicit checkout stage

        stage('Build') {
            steps {
                sh './mvnw clean package'
            }
        }
		
		stage('Upload to Artifactory') {
			steps {
				sh 'jfrog rt upload --url http://127.0.0.1:8380/artifactory/ --access-token ${ARTIFACTORY_ACCESS_TOKEN} target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar hestia-demo-generic/'
			}
		}
    }
	
    // post after stages, for entire pipeline, is also an implicit step albeit with explicit config here, unlike implicit checkout stage
    post {
        always {
            junit '**/target/surefire-reports/TEST-*.xml'
            archiveArtifacts 'target/*.jar'
        }
    }
}